#!/usr/bin/env bash
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." >/dev/null 2>&1 && pwd)"

pushd "$DIR" &> /dev/null

rm -rf bin || true
cp package.json package.bkp.json
lein do clean, cljsbuild once
rm package.json
mv package.bkp.json package.json

popd &> /dev/null
