#!/usr/bin/env bash
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." >/dev/null 2>&1 && pwd)"

from="$DIR/target/main.js"
to="$DIR/bin/main.js"

rm "$to" || true
mkdir "$DIR/bin" || true
mv "$from" "$to"
chmod a+x "$to"
